In [1]:
print("hello")

hello


In [2]:
import numpy as np

In [3]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
np.array([1, 2, 3, 5, 7, 12])

array([ 1,  2,  3,  5,  7, 12])

In [7]:
np.arange(3, 100)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
i = np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
i = np.arange(3, 10)
print(i)



[3 4 5 6 7 8 9]


In [15]:
np.random.rand(5, 2)

array([[0.44715063, 0.93433638],
       [0.90888145, 0.29332411],
       [0.58459831, 0.00395773],
       [0.89066228, 0.33431729],
       [0.81793459, 0.4864495 ]])

In [20]:
a = np.arange(5)
print(a)
b = a + 2
print(b)

[0 1 2 3 4]
[2 3 4 5 6]
